services:
  - type: web
    name: socialease-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backendkabi-main/socialease_backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 8000